{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ts-microservices-webapi.serviceAccountName" . }}
  labels:
{{ include "ts-microservices-webapi.labels" . | nindent 4 }}
{{- end -}}
